ci(docs): add a check for PR's to commit their doc changes
Repurpose the api-docs workflow to also run in all PR's but work only as
a check, if the changes in the PR introduce doc changes that are not
commited fail.

diff --git a/.github/workflows/api-docs.yml b/.github/workflows/api-docs.yml
--- a/.github/workflows/api-docs.yml
+++ b/.github/workflows/api-docs.yml
@@ -1,3 +1,5 @@
+# Autogenerate the API docs on new commit to important branches
+# Work as a check for PR's to not forget commiting their doc changes
 name: Autogenerate API docs
 on:
   push:
@@ -9,10 +11,12 @@ on:
       - 'master'
       - 'release-[0-9]+.[0-9]+'
   workflow_dispatch:
+  workflow_call:
 
 jobs:
   regen-api-docs:
     runs-on: ubuntu-20.04
+    if: github.event.pull_request.draft == false
     permissions:
       contents: write
       pull-requests: write
@@ -44,8 +48,14 @@ jobs:
           python3 scripts/gen_vimdoc.py
           printf '::set-output name=UPDATED_DOCS::%s\n' $([ -z "$(git diff)" ]; echo $?)
 
+      - name: PR has not commited doc changes
+        if: ${{ steps.docs.outputs.UPDATED_DOCS != 0 && github.event.pull_request }}
+        run: |
+          echo "Job failed, run ./scripts/gen_vimdoc.py and commit your doc changes"
+          exit 1
+
       - name: Automatic PR
-        if: ${{ steps.docs.outputs.UPDATED_DOCS != 0 }}
+        if: ${{ steps.docs.outputs.UPDATED_DOCS != 0 && !github.event.pull_request }}
         run: |
           git add -u
           git commit -m 'docs: regenerate [skip ci]'
